name: secrets
on: workflow_dispatch

jobs:
  test-job:
    environment: test
    env:
      DB_U: ${{vars.DB_USERNAME}}
      DB_P: ${{secrets.DB_PASSWORD}}
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        run: actions/checkout@v3
      - name: check env u
        run: echo ${{env.DB_U}}
      - name: checkout env p
        run: echo "p=${{env.DB_P}}"
  prod-job:
    environment: prod
    env:
      DB_U: ${{vars.DB_USERNAME}}
      DB_P: ${{secrets.DB_PASSWORD}}
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        run: actions/checkout@v3
      - name: check env u
        run: echo ${{env.DB_U}}
      - name: checkout env p
        run: echo "p=${{env.DB_P}}"
